name: My First Action
on: [pull_request]
jobs:
  exempel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print push success
        run: echo "pull request sucssesful!"

  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print files
        run: ls