name: My First Action
on: [push,pull_request]
jobs:
  exempel:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print PR success
        run: echo "pull request sucssesful!"

# en kommetar
  print:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print Push success
        run: echo "push detected"